# Generated by Django 4.2.3 on 2023-11-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=10)),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=20)),
                ('Place', models.CharField(max_length=30)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
