# Generated by Django 4.2.3 on 2023-11-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_name', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Category_id', models.IntegerField()),
                ('Price', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='foodBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_id', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
            options={
                'db_table': 'foodBooking',
            },
        ),
        migrations.CreateModel(
            name='tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_name', models.CharField(max_length=50)),
                ('chair_count', models.IntegerField()),
                ('Size', models.CharField(max_length=30)),
                ('Time', models.TimeField()),
                ('Price', models.CharField(max_length=30)),
                ('Image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'tables',
            },
        ),
    ]
